# Site settings
title: Phonyduck
email: phonyduck@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I got into lockpicking by stumbling upon a video on reddit. Someone linked to `/r/lockpicking`,
  Bosnianbills videos were watched - and wham - addicted.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://phonyduck.github.io" # the base hostname & protocol for your site
reddit_username: phonyduck
github_username:  phonyduck

# Build settings
markdown: kramdown

paginate: 10

author: Phonyduck

gems: [jekyll-paginate]
