# Site settings
title: Phonyduck
email: phonyduck@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "phonyduck" # the subpath of your site, e.g. /blog/
url: "http://phonyduck.github.io/phonyduck" # the base hostname & protocol for your site
twitter_username: phonyduck
github_username:  phonyduck

# Build settings
markdown: kramdown

paginate: 4

author: Your name

gems: [jekyll-paginate]
